In [2]:
import pandas as pd

# REPORT/SUMMARY OF THE CAPSTONE PROJECT #

<font color='grey'>
    
# Seattle vs. Vancouver (with Gdansk in the background) #
# Battle of Neighbourhoods #


## Background ##

__Jan Kowalski, PhD__ is a professor of data science at the Gdańsk University of Technology.
He specializes in the processing of natural languages, although other areas of data processing and data analysis are also of interest to him. He published numerous articles and books in his field of interest.

https://pg.edu.pl

and 

a professor of applied lingustics University of Gdańsk. 

https://ug.edu.pl

He specializes in the processing of natural languages, although other areas of data processing and data analysis are also of interest to him. He published numerous articles and books in his field of interest.
He is well known in international circles thanks to the participation in numerous seminars and other events where he delivers presentations of his extraordinary achievements.

He is 40 years old, single, devoted to his work.

He likes theatre and baroque music and contemporary art. From time to time he likes to watch a good film.
He also is an accomplished sailor.

Professor Kowalski regularly receives invitations from various foreign universities to come and to teach and run research there.

Recently he has received two invitations to work:

from 

__University of Seattle, Seattle, WA__

and

from

__University of British Columbia, Vancouver, BC__

Professor Kowalski is supposed to run classes for students of the universities in the following majors:

- data science
- data science in computational Linguistics.

He will also be able to continue his work in the area of processing natural languages.</fon>


<font color='blue'>

For the detailed course of work please see the notebook:

__SvV(3).ipynb__

also available in my github under the ulr:
    
https://github.com/btillack/Capstone_project/blob/main/SvV(3).ipynb </fon>

The notebook contains all the maps, pictures and all the information related to this project.

__I. INTRODUCTION__

The project covers the gathering of the information constituting the basis for the dicion of choosing between Seattle, WA and Vancouver, BC as a settlement place.

The decion will be made on the basis of socio-cultural basis.

Within the project we are choosing the city having a wider offering the following fields of interest:


| Fiekd of interest| Type of venue |
|------------------|---------------|
| contemporary art | Art gallery   | 
| baroque music    | Concert Hall / Music Venue |
| drama            | Theatre       |
| film             | Cinema        |
| sailing          | Yachtclub or Harbor / Marina    |

It is based on the ficticious character Jan Kowalski, PhD, professor of Polish universities in Gdańsk who was offered positions at competenig universities, one iin Seattle, and one i n Vancouver.
 

The list presented above was later extended by additional venue types:

| Field of interest | Type of venue |
|---|---|
|contemporary art | Arts & Crafts Store |
| | Museum |
| music and theatre | Performing Arts Venue |

The analysis may also be usful to other people considering moving to the West coast of America.

__II. GEO-LOCATION DATA SOURCES AND ACQUISITION__

_1. General location_

In the first step, we gather the location information about both cities.

The cities are shown on the maps to analyse the geographical aspects.

As a result we can conclude, the location of both cities make it easy for Prof. Kowalski to pursue his sailing activities.
Seattle is located on the shores of Puget Sound while
Vancouver lies on Georgia Strait
areas known among sailors as very intersting and demanding.


_2. Administrative division and clustering_

In order to analyse the socio-cultural offerings of both cities it is necessary to find the location of the most interesting venues.

As a starting point the data base of the postal codes was taken into consideration.

There is a publicly available full register of all postal codes in the US and Canada.

Filtering the codes of Vancouver and Seattle gave back still enormous database without the connection of the code to the name of the neighbourhood.

Therefore a different approach has been assumed, gather the information about neighbourhoods from the sites of Seattle and Vancouver municipalities.

Such gathered data was augmented by the information from Google Maps.

Such gathered data was prepared in the form of a csv-file and uploaded to the notebook.

As a result the dataframes containing the information on neighbourhoods in Seattle and Vancouver were createtd.


### Clustering ###

The neighbourhoods were clustered and presented in relation to the Universities.



__Vancouver Nieghbourhoods Clustering__
![Vancouver Neighbourhoods Clustering](vanc_clust_map.png)

__Seattle Neighbourhoods Clustering__
![Seattle Neighbourhoods Clustering](stle_clust_map.png)

This way the centroid of thecluster lying the nearest vicinity to the future worplace will be the central point for data sourcing from Foursquare.

Using the Foursquare profile we will import the information about the venues in both cities and analyse them regarding prof. Kowalski's personal preferences.

__III. DETAILED VENUE DATA AND ANALYSIS OF DATASETS__

### Data from Foursquare ###

To import the data from Foursquare the centres of particular centroids were chosen with the radius of 1000 m.


From the datasets received for both, Seattle and Vancouver only the venues of the particular type were selected.

Taking into account he interests of our fictitious character we analysed the number of venues of particular type in the set vicinity.
In order to measure the value of the results in light of the personal preferences of Prof. Kowalski we employed the table with weights of particular venue types. This will let to build the final mark best suited to Mr. Kowalski's liking.

Below, the datasets for Vancouver and Seattle present the grouping by the venue category.
This layout allows for analysing the preferences of our character:

__Vancouver Venues__

In [10]:
vanc=pd.read_csv('//Users/BoTi/Desktop/van-ven_cat.csv')
vanc

,Venue Category,Neighbourhood,Neighbourhood Latitude,Neighbourhood Longitude,Venue,Venue Latitude,Venue Longitude
0,American Restaurant,1,1,1,1,1,1
1,Art Gallery,2,2,2,2,2,2
2,Arts & Crafts Store,5,5,5,5,5,5
3,Asian Restaurant,4,4,4,4,4,4
4,Athletics & Sports,2,2,2,2,2,2
...,...,...,...,...,...,...,...
149,Video Store,1,1,1,1,1,1
150,Vietnamese Restaurant,10,10,10,10,10,10
151,Wine Shop,2,2,2,2,2,2
152,Women's Store,2,2,2,2,2,2
153,Yoga Studio,2,2,2,2,2,2

__Seattle Venues__

In [11]:
seat=pd.read_csv('//Users/BoTi/Desktop/stle_ven_cat.csv')
seat

,Venue Category,Neighbourhood,Neighbourhood Latitude,Neighbourhood Longitude,Venue,Venue Latitude,Venue Longitude
0,American Restaurant,5,5,5,5,5,5
1,Antique Shop,1,1,1,1,1,1
2,Arcade,1,1,1,1,1,1
3,Art Gallery,2,2,2,2,2,2
4,Arts & Crafts Store,3,3,3,3,3,3
...,...,...,...,...,...,...,...
139,Vietnamese Restaurant,6,6,6,6,6,6
140,Warehouse Store,2,2,2,2,2,2
141,Wine Bar,2,2,2,2,2,2
142,Winery,2,2,2,2,2,2
143,Yoga Studio,5,5,5,5,5,5

Extracting the right data from the above datasets allows to present the detailed information for each city, using the weighing factors as in the table below:


| Field of interest| Type of venue | Weight |
|------------------|---------------|---|
| contemporary art | Art gallery   | 20% |
| baroque music    | Concert Hall / Music Venue | 15% + 15% |
| drama            | Theatre       | 10%|
| film             | Cinema        | 5%|
| sailing          | Yachtclub or Harbor / Marina    | 35% |
|---|---|---|
|Total | - | 100% |


Below you can find the tables summarising the result of the survey including the weights assumed for the particular areas of interest of prof. Kowalski as below:

   

Results for Vancouver:
    
| Vanue Category | Number of instances | Weight | Result |
|---|---|---|---|
| Art Gallery | 2 | 20% | 0.40 |
| Concert Hall | 3 |15%| 0.45|
| Music Venue | 1 | 15% | 0.15 |
| Theater | 3 | 10% | 0.30 |
| Cinema | 0 | 5% | 0.00 |
| Harbor / Marina | 1 | 35% | 0.35 |
|---|---|---|---|
|TOTAL | 10 | 100% | 1.65 |    

Results for Seattle:
    
| Vanue Category | Number of instances | Weight | Result |
|---|---|---|---|
| Art Gallery | 2 | 20% | 0.40 |
| Concert Hall | 0 |15%| 0.00|
| Music Venue | 0 | 15% | 0.00 |
| Theater | 1 | 10% | 0.10 |
| Cinema | 0 | 5% | 0.00 |
| Harbor / Marina | 0 | 35% | 0.00 |
|---|---|---|---|
|TOTAL | 3 | 100% | 0.50 |




The above presented results obviously show that the __Vancouver's socio-cultural offer with 1.65 scoring is much richer  than Seattle's with scoring of 0.5.__

As Seattle performed very poorly in comparison to the Vancouver in the first attempt, Prof. Kowalski reviewed the list of venue categories and extended the search with changed weights to accomdate the extended list of venues.

                                    VANCOUVER, BC         SEATTLE.WA
|Venue Category	|Weight	|Number	|Points	|Number	|Points|
|---|---|---|---|---|---|
|Art Gallery	|15%	|2	|0,3	|2	|0,3|
|Concert Hall	|10%	|3	|0,3	|0	|0|
|Music Venue	|10%	|1	|0,1	|0	|0|
|Theatre	|8%	|3	|0,24	|1	|0,08|
|Cinema	|5%	|0	|0	|0	|0|
|Harbour/Marina	|25%	|1	|0,25	|0	|0|
|
|Int. total	|73%	|10	|1,19	|3	|0,38|
|
|Arts & Crafts Store	|12%	|5	|0,6	|3	|0,36|
|Museum	|5%	|1	|0,05	|1	|0,05|
|Performing Arts Venue	|10%	|2	|0,2	|2	|0,2|
|
|TOTAL	|100%	|18	|2,04	|9	|1,37|


__IV. VERIFICATION OF THE DATA QUALITY__

After performing the above analysis Prof. Kowalski was very supprised with the modesty of the socio-cultural offer of both cities.
He compares the offer of Seattle and Vancouver to what he can find in the Tri-City area (Gdańsk-Sopot-Gdynia) where he leaves now (approx. 700 thousand inhabitants).
There are more thetres, an opera, the philharmony and numerous museums and galleries. There are many events even off-season.
Notwithstanding, the very sailor-friendly Gulf of Gdańsk and Southern Baltic Sea.

__General information__
https://www.gdansk.pl/en/about-gdansk

__Cultural giude__(unfortunately, only in Polish)
https://kultura.trojmiasto.pl

__Pictures__
https://galeria.trojmiasto.pl/#Kultura_i_rozrywka


Therefore, to compare the quality of the data source, Prof. Kowalski decided to perform the analysis for his home town.
This way he will be able to see how "filtering" the limits imposed by Foursquare really are.

__GDANSK__

Prof.Kowalski repeted the whole procedure for his home-town, i.e.
1. he imported geo location data for the neighbourhoods (Wiki, gdansk.pl, Google Maps)
2. Clustered the neighbourhoods (as in the picture below)

![Gdansk clustering](gda_clust_map.png)

Knowing his home-town he would rather change the clustering in regard to Śródmieście-Główne Miasto neighbourhood.
This is so called "Old Town", a main historic centre of Gdańsk rich in historic and cultural venues and it was clustered together with the industrial districts.
The location of this neighbourhood was arbitrarily chosen as a centre of search in Foursquare.

However, at this moment we are testing the influence of the limits imposed by Foursquare and not the results of clustering.

__Sourcing and analysing the data from Foursquare__

As a result of the analysis it turned out that the socio-cultural offering of Gdańsk in not much better than the offering of Seattle.

                                       GDAŃSK	

|Venue Category|	Weight|	Number|	Points|
|----|----|----|----|
|Art Gallery|	15%|	6	|0,9|
|Concert Hall|	10%|	1	|0,1|
|Music Venue|	10%|	0	|0|
|Theatre	|8%|	1	|0,08|0|
|Cinema	|5%	|0	|0|
|Harbour/Marina	|25%	|0	|0|
|
|Int. total	|73%	|8	|1,08|
|
|Arts & Crafts Store|	12%|	0|	0|
|Museum and Historic Site |	5%	|8	|0,4|
|Performing Arts Venue	|10%	|0	|0|
|
|TOTAL|	100%	|16	|1,48|

This was a surprise to Prof. Kowalski because he is abreast of the cultural events taking place in Gdańsk and knows most of the cultural venues of the types used in this analysis. In his opinion Gdańsk should have gathered much more points but he observed the following shortcomings of the data set:
- the list did not contain OPERA as a separate category,
- CINEMAs, non-existent and although the cinematic multiplexes are usually parts of the shopping malls, there are still indepenent one-hall (studio) cinemas in Gdańsk,
- his prefered venues - MARINAs - are located on the Eastern part of the city farther then 1 km from the city-centre.

__V. CONCLUSION__

Bearing on the gathered data the conclusiuon is prety obvious.

the rankiing shows that Vancouver gathered 2.04 points while Seattle - 1.37. 

Vancouver is, therefore, a better choice than Seattle assuming everything else being equal, especially academic opportunities.

### Therefore Prof. Kowalski should accept the proposal from the University of British Columbia in Vancouver, BC. ###

The decision will be easier to make as the comparison with his home-town showed the advantage of Vancouver over Gdańsk, too.
Knowing Gdańsk and its socio-cultural life, in Prof. Kowalski's opinion the data from Foursquare does not show the full potential of the city of Gdańsk. This same conclusion must be applied also to both contenders, i.e. the results must be deemed acceptable.

__VI. Obserwations__

This notebook contains venue data for the radius r=1000 m.
But the test was done with the radius r=2500 m in an attempt to widen the area in search for POIs. The results received were the same as in the case of radius r=1000 m. Increasing the radius did not bringthe expected results as the limit on number of venues is 100 and cannot be increased and is the main limiting factor for this analysis.

__VII. PRESENTATION__

_The project will be presented inthe form of the_ __text__ _document and posted to my github where it will be publicly accessible._